# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Pokemaster' do
  use_frameworks!

  # Pods for Pokemaster
  pod 'MBProgressHUD', '~> 0.9'
  pod 'Alamofire', '~> 3.4'
  pod "Unbox"
  pod 'SwiftyJSON'

  target 'PokemasterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
